### ISSUE TITLE
Fails to load on 1.21

### ISSUE THREAD

**Issue by DBTDerpbox** [kejonaMC/CrossplatForms#195]
### Describe the bug

The plugin is unable to load in 1.21 in its current state. This results in all of its functionality being unavailable.

### To Reproduce

- Set up a Paper 1.21 server
- Add the plugin
- Error appears in log

```
[16:34:06 INFO]: [CForms] Enabling CrossplatForms v1.5.0
[16:34:06 ERROR]: Error occurred while enabling CrossplatForms v1.5.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at CrossplatForms-Spigot.jar/dev.kejona.crossplatforms.spigot.CrossplatFormsSpigot.findVersionAdapter(CrossplatFormsSpigot.java:28) ~[CrossplatForms-Spigot.jar:?]
        at CrossplatForms-Spigot.jar/dev.kejona.crossplatforms.spigot.SpigotBase.onEnable(SpigotBase.java:80) ~[CrossplatForms-Spigot.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-119-100d75a]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-119-100d75a]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-119-100d75a]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-119-100d75a]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at CrossplatForms-Spigot.jar/dev.kejona.crossplatforms.spigot.ClassNames.<clinit>(ClassNames.java:25) ~[CrossplatForms-Spigot.jar:?]
        ... 14 more
[16:34:06 INFO]: [CForms] Disabling CrossplatForms v1.5.0
```

### Expected behaviour

The plugin would not give an error and would allow server admins and players to use its features.

### Server Version and Plugins

Paper 1.21-119-master@100d75a (2024-07-29T16:00:13Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### Geyser Dump

https://dump.geysermc.org/mg8VxiD53kq8qQik350QMnfOxpYz3LP2

### CrossplatForms Version

1.5.0

### Additional Context

[latest.log](https://github.com/user-attachments/files/16419351/latest.log)

**Comment by ZherKing** [comment]
I am also waiting for the fix of this issue

**Comment by MiguVT** [comment]
me too, there is a 1.21 branch i will try to compile to see if it fixs it

**Comment by MiguVT** [comment]
Dont tested, compiled with java 21 (Requires Java 21)
[CrossplatForms-Spigot.zip](https://github.com/user-attachments/files/16429226/CrossplatForms-Spigot.zip)

Uploaded as zip because github dont allow to upload it as jar

**Comment by ZherKing** [comment]
> Dont tested, compiled with java 21 (Requires Java 21) [CrossplatForms-Spigot.zip](https://github.com/user-attachments/files/16429226/CrossplatForms-Spigot.zip)
> 
> Uploaded as zip because github dont allow to upload it as jar

I tried to launch the plugin you sent in Java 22 and found that it started normally in the /plugins command. I haven't tested it yet, I guess he's fine

**Comment by MiguVT** [comment]
♥️ I will try it now, i was updating all my server plugins, lets check if it works (Remember, its a snapshot of a version that is not released, it can contain bugs but there is no updates on the version in the last month, so i think it works fine with no bugs.

**Comment by Jens-Co** [comment]
The compiled jar from this branch should work on 1.21 server, it's not yet in master as i did not had time to properly test it. I lack the time to properly implement the 1.21 or 1.20.6 for that matter. 

If you have question feel free to ask.

**Comment by MiguVT** [comment]
Its working, no bugs atm, if i find some bugs i will report it here and make a PR if i can fix it

**Comment by Jens-Co** [comment]
Great thanks, the main issue lies in the nms, we should be looking for a way to remove nms completely in the future.

**Comment by DBTDerpbox** [comment]
I'm not sure why I didn't bother checking to see if there was an updated branch, thank you

**Comment by lolwhatdidigetbanned** [comment]
> Dont tested, compiled with java 21 (Requires Java 21) [CrossplatForms-Spigot.zip](https://github.com/user-attachments/files/16429226/CrossplatForms-Spigot.zip)
> 
> Uploaded as zip because github dont allow to upload it as jar

Add a bungee cord compiled version this ;]

**Comment by lolwhatdidigetbanned** [comment]
[jar file for 1.21 spigot only]
@MiguVT thanks to him but it’s easier now https://drive.google.com/file/d/1OB3slajqR7mQrlHYklF5E8nDkLlslY09/view?usp=sharing

**Comment by MiguVT** [comment]
> > Dont tested, compiled with java 21 (Requires Java 21) [CrossplatForms-Spigot.zip](https://github.com/user-attachments/files/16429226/CrossplatForms-Spigot.zip)
> > Uploaded as zip because github dont allow to upload it as jar
> 
> Add a bungee cord compiled version thxs ;]

Just compile by yourself, i found it on my computer, it can be this version but im not sure, just try: https://mega.nz/file/A7NBDK5L#I15bBH9u9NIqkhQhzxzESyTHyRTMtY8k-Fscghjo5KQ

**Comment by MiguVT** [comment]
> thanks to him but it’s easier now https://drive.google.com/file/d/1OB3slajqR7mQrlHYklF5E8nDkLlslY09/view?usp=sharing

https://mega.nz/file/Ii8WCIiY#qU-pmrBgObUfnGAUNnnWVMrwbgCMvfxgvQu81KCMmPg
Here is a mega link, drive link give error because tos

**Comment by lolwhatdidigetbanned** [comment]
> > thanks to him but it’s easier now https://drive.google.com/file/d/1OB3slajqR7mQrlHYklF5E8nDkLlslY09/view?usp=sharing
> 
> https://mega.nz/file/Ii8WCIiY#qU-pmrBgObUfnGAUNnnWVMrwbgCMvfxgvQu81KCMmPg Here is a mega link, drive link give error because tos

I know it does but I will fix that

**Comment by MiguVT** [comment]
> lack the time to properly implement the 1.21 or

I was using it a month and everything is working without bugs or errors (purpur 1.21) ♥️

**Comment by lolwhatdidigetbanned** [comment]
> > lack the time to properly implement the 1.21 or
> 
> I was using it a month and everything is working without bugs or errors (purpur 1.21) ♥️

Same❤️ still works bedrock server functioning

**Comment by Konicai** [comment]
If you have a fix for anything you can create a PR, which will provide downloads. Please do NOT link external jar downloads of any type here.

**Comment by MiguVT** [comment]
> If you have a fix for anything you can create a PR, which will provide downloads. Please do NOT link external jar downloads of any type here.

Oh ok, sorry, i dont fixed anything, i just compiled it, can you upload or run an action for get the 1.21 CrossplatForms download?? tysm, too much servers use it and i know how to compile but too many people dont know.

**Comment by Jens-Co** [comment]
You can find a compiled 1.21 dev build on our discord channel.

**Comment by Konicai** [comment]
Use the builds available on https://ci.kejonamc.dev/job/CrossplatForms/job/dev/ please

**Comment by DBTDerpbox** [comment]
Coming back to this, you're probably aware but the latest development build (using [https://ci.kejonamc.dev/job/CrossplatForms/job/dev/](https://ci.kejonamc.dev/job/CrossplatForms/job/dev/)) is incompatible with 1.21.3, not sure if this should of been a new issue or not, so I'm sorry if it should of been

Log:
[latest.log](https://github.com/user-attachments/files/17689207/latest.log)

**Comment by MiguVT** [comment]
Rn we don't need to request an update, it should be an issue when stable 1.21.3 paper released

**Comment by VincentX0905** [comment]
Where is the 1.21.0/1 1.21.2 update?
Now it is version 1.21.3
1.21.4 will be released in a few weeks.

When will it be updated? @Konicai

**Comment by VincentX0905** [comment]
I created version 1.21.3 of the plugin
Remember: This is just a hotfix and will not replace future versions.(so you can update first)
Please wait for the author's maintenance version for the official version

[Hotfix Version](https://github.com/VincentX0905/CrossplatForms-new)
`Select "Actions" in the upper navigation bar -> Select the latest workflows --> Check out the Artifacts below and download and unzip it` [need login]

If you have any questions please open an issue in my repository
I will try to update to 1.21.4 in the next few days

>In versions after 1.20.5, PaperMC has removed the NMS acquisition method.
> Therefore, you cannot use `Bukkit.getServer().getClass().getPackage().getName()` to obtain the NMS version on PaperMC or PaperMC branch (purpur etc.) servers.
> [Announcement link](https://discord.com/channels/289587909051416579/1077385604012179486/1155459001090318346)

**Comment by wykwey** [comment]
> I created version 1.21.3 of the plugin Remember: This is just a hotfix and will not replace future versions.(so you can update first) Please wait for the author's maintenance version for the official version
> 
> [Hotfix Version](https://github.com/VincentX0905/CrossplatForms-new) `Select "Actions" in the upper navigation bar -> Select the latest workflows --> Check out the Artifacts below and download and unzip it`
> 
> If you have any questions please open an issue in my repository I will try to update to 1.21.4 in the next few days
> 
> > In versions after 1.20.5, PaperMC has removed the NMS acquisition method.
> > Therefore, you cannot use `Bukkit.getServer().getClass().getPackage().getName()` to obtain the NMS version on PaperMC or PaperMC branch (purpur etc.) servers.
> > [Announcement link](https://discord.com/channels/289587909051416579/1077385604012179486/1155459001090318346)


Can you build and publish a jar

**Comment by VincentX0905** [comment]
> > I created version 1.21.3 of the plugin Remember: This is just a hotfix and will not replace future versions.(so you can update first) Please wait for the author's maintenance version for the official version
> > [Hotfix Version](https://github.com/VincentX0905/CrossplatForms-new) `Select "Actions" in the upper navigation bar -> Select the latest workflows --> Check out the Artifacts below and download and unzip it`
> > If you have any questions please open an issue in my repository I will try to update to 1.21.4 in the next few days
> > > In versions after 1.20.5, PaperMC has removed the NMS acquisition method.
> > > Therefore, you cannot use `Bukkit.getServer().getClass().getPackage().getName()` to obtain the NMS version on PaperMC or PaperMC branch (purpur etc.) servers.
> > > [Announcement link](https://discord.com/channels/289587909051416579/1077385604012179486/1155459001090318346)
> 
> Can you build and publish a jar

Just check out https://github.com/VincentX0905/CrossplatForms-new/actions
And read https://github.com/kejonaMC/CrossplatForms/issues/195#issuecomment-2542594371
If you don't look carefully, you won't be able to get the Jar file

**Comment by Jens-Co** [comment]
> e any questions please open an issue in my repository I will try to update to 1.21.4 in the next few days
> 
> > In versions after 1.20.5, PaperMC has removed the NM

Hello Vincent, i totally missed papers announcement  about that one. There is currently a dev branch that had working plugin, I lack the time to look into some other isssues aswel for example the nms location of craftplayer class. 

Feel free to make a PR with a proper fix if you feel like it.

**Comment by VincentX0905** [comment]
> > e any questions please open an issue in my repository I will try to update to 1.21.4 in the next few days
> > > In versions after 1.20.5, PaperMC has removed the NM
> 
> Hello Vincent, i totally missed papers announcement about that one. There is currently a dev branch that had working plugin, I lack the time to look into some other isssues aswel for example the nms location of craftplayer class.
> 
> Feel free to make a PR with a proper fix if you feel like it.

@Jens-Co Hello!
I only did a hotfix, this is not a long-term solution.
https://github.com/VincentX0905/CrossplatForms-new/blob/e71ecdf1fc6daa867f041ac9dafb7a7062fef218/spigot-common/common/src/main/java/dev/kejona/crossplatforms/spigot/ClassNames.java#L26-L45
You need to find a NMS plugin for gradle or some other solution (maybe remove NMS?) for a long term solution

**Comment by VincentX0905** [comment]
https://github.com/kejonaMC/CrossplatForms/pull/211

**Comment by VincentX0905** [comment]
1.21.4 Hotfix has been tested and released

> 1.21.3: https://github.com/VincentX0905/CrossplatForms-new/actions/runs/12325135733
> 1.21.4: https://github.com/VincentX0905/CrossplatForms-new/actions/runs/12329571043
