### ISSUE TITLE
1.20.6 Support?

### ISSUE THREAD

**Issue by DinoFengz** [kejonaMC/CrossplatForms#197]
### What feature do you want to see added?

1.20.5/6 support for the plugin

### Are there any alternatives?

-

**Comment by Konicai** [comment]
Have you tried it? If it does not work, use https://ci.kejonamc.dev/job/CrossplatForms/job/dev/

**Comment by DinoFengz** [comment]
Even with the dev version also not working.
```
[15:56:20 INFO]: [PluginRemapper] Remapping plugin 'plugins/CrossplatForms-Spigot.jar'...
[15:56:23 INFO]: [PluginRemapper] Done remapping plugin 'plugins/CrossplatForms-Spigot.jar' in 2978ms.
[15:56:28 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[15:56:28 INFO]: Found new data pack file/bukkit, loading it automatically
[15:56:28 INFO]: Found new data pack paper, loading it automatically
[15:56:29 INFO]: No existing world data, creating new world
[15:56:29 INFO]: Loaded 1175 recipes
[15:56:30 INFO]: Loaded 1276 advancements
[15:56:30 INFO]: Starting minecraft server version 1.20.6
[15:56:30 INFO]: Loading properties
[15:56:30 INFO]: This server is running Paper version 1.20.6-149-ver/1.20.6@6e71f41 (2024-08-24T09:37:06Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
[15:56:32 INFO]: Server Ping Player Sample Count: 12
[15:56:32 INFO]: Using 4 threads for Netty based IO
[15:56:33 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 2 worker threads, and gen parallelism of 2 threads
[15:56:33 WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[15:56:33 INFO]: Default game type: SURVIVAL
[15:56:33 INFO]: Generating keypair
[15:56:33 INFO]: Starting Minecraft server on 0.0.0.0:12121
[15:56:33 INFO]: Using epoll channel type
[15:56:33 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[15:56:33 INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
[15:56:34 INFO]: [CForms] Loading server plugin CrossplatForms v1.5.0
[15:56:34 INFO]: Preparing level "world"
[15:56:41 INFO]: Preparing start region for dimension minecraft:overworld
[15:56:45 INFO]: Time elapsed: 3916 ms
[15:56:45 INFO]: Preparing start region for dimension minecraft:the_nether
[15:56:45 INFO]: Time elapsed: 698 ms
[15:56:45 INFO]: Preparing start region for dimension minecraft:the_end
[15:56:46 INFO]: Time elapsed: 444 ms
[15:56:46 INFO]: [CForms] Enabling CrossplatForms v1.5.0
[15:56:46 INFO]: v1_20_R1
[15:56:46 ERROR]: Error occurred while enabling CrossplatForms v1.5.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at CrossplatForms-Spigot.jar/dev.kejona.crossplatforms.spigot.CrossplatFormsSpigot.findVersionAdapter(CrossplatFormsSpigot.java:29) ~[CrossplatForms-Spigot.jar:?]
        at CrossplatForms-Spigot.jar/dev.kejona.crossplatforms.spigot.SpigotBase.onEnable(SpigotBase.java:80) ~[CrossplatForms-Spigot.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Class for name org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer
        at java.base/java.util.Objects.requireNonNull(Objects.java:259) ~[?:?]
        at CrossplatForms-Spigot.jar/dev.kejona.crossplatforms.utils.ReflectionUtils.requireClass(ReflectionUtils.java:28) ~[CrossplatForms-Spigot.jar:?]
        at CrossplatForms-Spigot.jar/dev.kejona.crossplatforms.spigot.ClassNames.<clinit>(ClassNames.java:57) ~[CrossplatForms-Spigot.jar:?]
        ... 14 more
[15:56:46 INFO]: [CForms] Disabling CrossplatForms v1.5.0
[15:56:46 INFO]: Running delayed init tasks
[15:56:46 INFO]: Done (16.343s)! For help, type "help"
container@daemon~ Server marked as running...
[15:56:46 INFO]: *************************************************************************************
[15:56:46 INFO]: This is the first time you're starting this server.
[15:56:46 INFO]: It's recommended you read our 'Getting Started' documentation for guidance.
[15:56:46 INFO]: View this and more helpful information here: https://docs.papermc.io/paper/next-steps
[15:56:46 INFO]: *************************************************************************************
[15:56:46 INFO]: Timings Reset
plugins
[15:57:02 INFO]: Server Plugins (1):
[15:57:02 INFO]: Bukkit Plugins:
[15:57:02 INFO]:  - CrossplatForms
```

**Comment by Konicai** [comment]
Thanks
